services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "127.0.0.1:1883:1883" #for binding mosquitto 1883 to localhost
      - "8883:8883" #public mqtt over tls
      - "9001:9001" #for browser client web sockets
    volumes:
      - ./mosquitto/config:/mosquitto/config:ro #give container access to hostt managed certs at runtime
      - ./mosquitto/certs:/mosquitto/certs:ro
      - ./mosquitto/passwd:/mosquitto/passwd:ro #mount repo's pwfile and acl file into the container so mosquitto can encorce authentication (pwfile) && authoriztion (aclfile)
      - ./mosquitto/acl:/mosquitto/acl:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mosquitto_sub -h localhost -p 1883 -t '$$SYS/broker/uptime' -C 1 >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: ["mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    container_name: timescaledb
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./timescaledb/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 10s
      timeout: 5s
      retries: 10

  ingestor:
    build: ./services/ingestor
    container_name: ingestor
    depends_on:
      mosquitto:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
    env_file:
      - ./services/ingestor/.env
    environment:
      MQTT_HOST: mosquitto
      MQTT_PORT: "1883"
    restart: unless-stopped

volumes:
  mosquitto_data:
  mosquitto_log:
  timescale_data:

networks:
  internal:
    driver: bridge